name: pinn
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - "numpy<2"
  - requests
  - "ase>=3.22.0,<3.23.0"
  - "click>=7.0,<8.0"
  - "pyyaml>=6.0.1,<6.1.0"
  - pytest
  - pytest-forked
  - pip:
      # Torch (fast wheels)
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch
      - torchvision
      - torchaudio
      # TensorFlow: CPU-only, minimal
      - tensorflow-cpu==2.8.0
      - protobuf<3.20